export enum EventType {
	ALLIANCE_CREATED = "alliance_created",
	ALLIANCE_EXPIRES = "alliance_expires",
	BUILDING_CREATED = "building_created",
	BUILDING_DEMOLISHED = "building_demolished",
	BUILDING_LOOTED = "building_looted",
	BUILDING_UPGRADED = "building_upgraded",
	FACTION_CREATED = "faction_created",
	FACTION_DIES = "faction_dies",
	FACTION_JOINS_ALLIANCE = "faction_joins_alliance",
	FACTION_LEAVES_ALLIANCE = "faction_leaves_alliance",
	FIGHT = "fight",
	PLAYER_CREATED = "player_created",
	PLAYER_DIES = "player_dies",
	PLAYER_MADE_PRISONER = "player_made_prisoner",
	PLAYER_JOINS_FACTION = "player_joins_faction",
	PLAYER_LEAVES_FACTION = "player_leaves_faction",
	PLAYER_HIRED_AS_MERCENARY = "player_hired_as_mercenary",
	PLAYER_MOVES = "player_moves",
}
